### ISSUE TITLE
import src.config error

### ISSUE THREAD

**Issue by yyunhh** [zhuhao-nju/hmd#19]
Hello, thanks for ur work!

I plan to run the datasets/proc_all_data.py to get all the dataset.
But I encounter the issue:

```
ubuntu@server~/Desktop/hmd/datasets$ python proc_all_data.py
Traceback (most recent call last):
  File "proc_all_data.py", line 6, in <module>
    from LSP import proc_lsp
  File "/home/ubuntu/Desktop/hmd/datasets/LSP.py", line 14, in <module>
    from hmr_predictor import hmr_predictor
  File "/home/ubuntu/Desktop/hmd/datasets/../src/hmr_predictor.py", line 26, in <module>
    import src.config
ModuleNotFoundError: No module named 'src.config'

```

Is there any missing file(config) in src folder?
(I have already used ```pip install src```)

Thanks in advance : )

**Comment by wangsen1312** [comment]
@yyunhh The src.config here is the path for HMR src/config.py
In the second line of conf.ini, you should change it to your own path.
Hope it can help you

**Comment by yyunhh** [comment]
@wangsen1312 
OMG, thank you a lot for your help!

May I ask another question about the LSP and LSPET dataset?
It seems that their website is closed right now?

If I run the datasets/proc_all_data.py can I get these two datasets?

![Datapro](https://user-images.githubusercontent.com/72399747/125730575-b8d48034-bb2d-422f-9e18-37748a1b857c.PNG)

```
LSP. Acquire the data from http://sam.johnson.io/research/lsp.html by clicking "Download (ZIP file)". Extract the data and set the extracting path to lsp_path.

LSPet. Acquire the data from http://sam.johnson.io/research/lspet.html by clicking "Dataset (ZIP file)". Extract the data and set the extracting path to lspet_path.
```

**Comment by wangsen1312** [comment]
@yyunhh We need download the dataset first. The datasets/proc_all_data.py only do the preprocess part without download.

I found some codebase such as https://dbcollection.readthedocs.io/en/latest/datasets/leeds_sports_pose.html  can still offer dataset download.

Hope it can help.

**Comment by yyunhh** [comment]
@wangsen1312 
Hello, recently the website is open again : )

Thanks a lot for ur reply!

**Comment by alsehaimaa** [comment]
> Hello, thanks for ur work!
> 
> I plan to run the datasets/proc_all_data.py to get all the dataset. But I encounter the issue:
> 
> ```
> ubuntu@server~/Desktop/hmd/datasets$ python proc_all_data.py
> Traceback (most recent call last):
>   File "proc_all_data.py", line 6, in <module>
>     from LSP import proc_lsp
>   File "/home/ubuntu/Desktop/hmd/datasets/LSP.py", line 14, in <module>
>     from hmr_predictor import hmr_predictor
>   File "/home/ubuntu/Desktop/hmd/datasets/../src/hmr_predictor.py", line 26, in <module>
>     import src.config
> ModuleNotFoundError: No module named 'src.config'
> ```
> 
> Is there any missing file(config) in src folder? (I have already used `pip install src`)
> 
> Thanks in advance : )

I didn't find any  config.py in scr any help please

**Comment by wangsen1312** [comment]
@alsehaimaa The src.config here is the path for HMR src/config.py
